apiVersion: v1
kind: Service
metadata:
  name: {{ include "nmbn-exporter.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
  {{- include "nmbn-exporter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "nmbn-exporter.selectorLabels" . | nindent 4 }}
  port:
  - name: metrics
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: 9279
